### ISSUE TITLE
Cannot find module - vue

### ISSUE THREAD

**Issue by narduin** [maplibre/maplibre-gl-directions#112]
Hello!

I'm trying to use this module with a vue project (nuxt 2).
I've installed and used `maplibre-gl` without problem.

I'm getting the error `Cannot find module '@maplibre/maplibre-gl-directions'` when I try to load my page.
Here is my code:

```js
import maplibregl from 'maplibre-gl'
import MapLibreGlDirections, { LoadingIndicatorControl } from '@maplibre/maplibre-gl-directions'

export default {
  data() {
    return {
      map: {},
    }
  },
  mounted() {
    this.createMap()
  },
  methods: {
    // MAP INIT
    createMap() {
      this.map = new maplibregl.Map({
        container: 'map',
        style: `https://api.maptiler.com/maps/streets/style.json?key=${this.style_token}`,
        center: this.center,
        zoom: 11,
      })
      this.map.addControl(new maplibregl.NavigationControl(), 'top-left')
      // DIRECTIONS INIT
      this.initDirections()
    },

    initDirections() {
      const directions = new MapLibreGlDirections(this.map)
      directions.interactive = true
      this.map.addControl(new LoadingIndicatorControl(directions))
    },
  },
}
```

I've tried different ways of initializing the `MapLibreGlDirections` in the code but it won't change the `Cannot find module` error.

Thanks!

**Comment by smellyshovel** [comment]
Hi @narduin, thanks for opening the issue.

It seems really wierd to me. Are you sure the package is added to your package.json? Which version do you use?

**Comment by smellyshovel** [comment]
There's also a problem with your code (I doubt it has anything to do with the issue, but still).

You invoke `this.initDirections()` when the map is not yet ready. Change it to

```typescript
this.map.on("load", () => this.initDirections())
```

**Comment by narduin** [comment]
From package.json: `"@maplibre/maplibre-gl-directions": "^0.1.6"`
I'm using yarn v3.2.1

Thanks for the correction on the initDirections, I think I've tried this but it did not fix the error so I reverted back.

**Comment by smellyshovel** [comment]
@narduin yeah, it has nothing to do with the issue for sure, just let you know that it won't work the way you did it when the issue will be resolved.

Don't you by any chance have a deployed reproduction of your environment?

**Comment by narduin** [comment]
I'm creating a codesandbox, I'll post it once its ready :)

**Comment by smellyshovel** [comment]
@narduin thank you! Please, ping me when it's done.

**Comment by narduin** [comment]
It seems the problems comes from another dependency.
I was able to create a [working codesandbox](https://codesandbox.io/s/mystifying-chatterjee-457gez?file=/pages/index.vue) example but as soon as I added my other two dependencies it broke (see [sandbox 2 with](https://codesandbox.io/s/serene-kalam-hbpvje?file=/package.json) `core-js` and `@nuxtjs/axios`).
Removing them does not fix anything…

**Comment by smellyshovel** [comment]
@narduin trying to fix your issue...
I'm thinking of default Nuxt's import-aliases that treat the `@` symbol as an alias for `/src`. Though I'm not entirely sure. Investigating.

**Comment by narduin** [comment]
Thank you, if you need anything else just ask!
In another branch I'm able to import `import { GeocoderAutocomplete } from '@geoapify/geocoder-autocomplete'` without problem.

**Comment by smellyshovel** [comment]
@narduin I've been able to narrow it down to this:

```
Must use import to load ES Module: /sandbox/node_modules/@maplibre/maplibre-gl-directions/dist/maplibre-gl-directions.es.js require() of ES modules is not supported. require() of /sandbox/node_modules/@maplibre/maplibre-gl-directions/dist/maplibre-gl-directions.es.js from /sandbox/node_modules/vue-server-renderer/build.dev.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename maplibre-gl-directions.es.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /sandbox/node_modules/@maplibre/maplibre-gl-directions/package.json.
```

Related issue: https://github.com/nuxt/nuxt.js/issues/9223

Seems to me like the nuxt's/webpack's issue, though it still may require me to build a CJS version of the lib. I don't want to do so though, because it's a somewhat legacy stuff.

I'll try to find a workaround for Nuxt now.

**Comment by narduin** [comment]
Thanks a lot!!
