### ISSUE TITLE
Personal Access Token in CI

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-directions#114]
@smellyshovel if I remember correctly, CI uses a personal access token somewhere. Is it `secrets.GITHUB_TOKEN`? It would be great if you could document somewhere what GitHub secrets are used in CI and maybe it would make sense give the personal access token a more explicit name like `secrets.MAINTAINER_PAT` or so. Thanks!

**Comment by smellyshovel** [comment]
@wipfli hmm.. TBH, the "MAINTAINER_PAT" doesn't mean anything at all to me. What did you mean by that?

The token used for Actions is called "GH_TOKEN" which is almost the same as the officially-documented "GITHUB_TOKEN" (that's available by default for any repo, but doesn't have enough permissions for our case). So I think if we decide to change its name, it should preserve the original one, but at the same time somehow represent that it has slightly more permissions to it. Something like "SUPER_GITHUB_TOKEN"? Or "PRIVILEGED_GITHUB_TOKEN "?

**Comment by smellyshovel** [comment]
Ah, "PAT" in your suggested name means "Personal Access Token", right? Yeah, I think it also makes sense to indicate that it's a personal token, not an organization one.

**Comment by smellyshovel** [comment]
I suggest something like "PRIVILEGED_GITHUB_PAT" then. The "privileged" I'm not sure about though.

**Comment by wipfli** [comment]
Sounds good to me. In any case, a readme about how the CI is set-up and what secrets it needs would be super helpful for future maintainers.

**Comment by smellyshovel** [comment]
@wipfli OK, thanks for the clarifications. I'll try my best to give it a look till v1.x, hoping that it's not urgent at the moment.

**Comment by wipfli** [comment]
Great thanks, @smellyshovel. This is not urgent...
