### ISSUE TITLE
Fix missing images at the NPM website

### ISSUE THREAD

**Issue by smellyshovel** [maplibre/maplibre-gl-directions#15]
We'll probably need to host the demo images somewhere in order for them to be correctly displayed
![Screenshot_20220414_181255](https://user-images.githubusercontent.com/9782236/163408943-fe8223ed-1fdf-49ee-9eb2-3c9b7249f8e4.png)
.

**Comment by wipfli** [comment]
I think you can use the github raw url.

**Comment by wipfli** [comment]
https://raw.githubusercontent.com/maplibre/maplibre-gl-directions/main/demo/src/assets/screenshots/1.png
