### ISSUE TITLE
Can't drag the map if setting directions.interactive = true

### ISSUE THREAD

**Issue by cj-neo** [maplibre/maplibre-gl-directions#169]
If I setting directions.interactive = true the map can't be moved by dragging

ERROR MESSAGE:

Uncaught TypeError: Cannot read properties of undefined (reading 'source')
    at He.onDragDown (main.ts:394:21)
    at Map.fire (maplibre-gl.js:31:11764)
    at fo._firePreventable (maplibre-gl.js:35:288967)
    at fo.mousedown (maplibre-gl.js:35:288284)
    at Yo.handleEvent (maplibre-gl.js:35:311286)

DEMO does not have this problem, is it an environment setting error? thx

**Comment by smellyshovel** [comment]
@cj-neo Hi. Thanks for reporting your issue.
Since it's not an issue with the Demo, can you please atatch the code?
Also would be nice if you tried to reproduce it somewhere on codesandbox/stackblitz or wherever else.

**Comment by cj-neo** [comment]
thanks for your reply

here is my code. Can be executed directly (click any two points to create directions,but can't move map by dragging)

[https://codesandbox.io/s/practical-gould-3bs93u](https://codesandbox.io/s/practical-gould-3bs93u)

I have found that the bug in the openstreetmap style, if change the style to

`style: "https://demotiles.maplibre.org/style.json",`

it works fine, but I don't know how to fix it

**Comment by smellyshovel** [comment]
@cj-neo Please, update the plugin's version o 0.2.5 and tell us whether the issue's gone.

**Comment by cj-neo** [comment]
Yes the bug has been fixed, thanks for your quick assistance :P

**Comment by smellyshovel** [comment]
Thanks @Miguel-Sanches
