### ISSUE TITLE
Fix publish workflow

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-directions#2]
https://github.com/maplibre/maplibre-gl-directions/runs/5884525408?check_suite_focus=true currently fails

**Comment by wipfli** [comment]
Maybe the NPM token is not shared with this repo. Let me check.

**Comment by smellyshovel** [comment]
Please, keep me updated

**Comment by smellyshovel** [comment]
@wipfli any updates so far?

**Comment by wipfli** [comment]
Does this repo have access to the NPM token @nyurik ?

**Comment by nyurik** [comment]
Afk, will check in a bit

**Comment by wipfli** [comment]
https://www.npmjs.com/package/@maplibre/maplibre-gl-directions

**Comment by wipfli** [comment]
Uff, the images on the npm website don't work.

**Comment by wipfli** [comment]
But anyway, congrats to your NPM package :)
