### ISSUE TITLE
Route not showing up. How to use with react-map-gl? 

### ISSUE THREAD

**Issue by 861** [maplibre/maplibre-gl-directions#230]
Hi, I am trying to use MapPrivder and useMap Hook with maplibre-gl-directions, but the route not showing up. 

Any suggestions? 

Thanks in advance!

**Comment by smellyshovel** [comment]
@861 

Hi. Not sure what are those. `useMap` hook is something from react? What's `MapPrivder`?

**Comment by 861** [comment]
@smellyshovel 
Thanks for your reply. 

I am trying to use [maplibre-gl-directions](https://github.com/maplibre/maplibre-gl-directions) with [react-map-gl](https://github.com/visgl/react-map-gl)

Both `useMap` and `MapProvider` are from react-map-gl.

Here is an example: 

`import {MapProvider, Map, useMap} from 'react-map-gl/maplibre';

function Root() {
  return (
    <MapProvider>
      <Map id="myMapA" ... />
      <Map id="myMapB" ... />
      <NavigateButton />
    </MapProvider>
  );
}

function NavigateButton() {
  const {myMapA, myMapB} = useMap();

  const onClick = () => {
    myMapA.flyTo({center: [-122.4, 37.8]});
    myMapB.flyTo({center: [-74, 40.7]});
  };

  return <button onClick={onClick}>Go</button>;
}`


full example: https://github.com/visgl/react-map-gl/tree/7.1-release/examples/get-started/hook

**Comment by 861** [comment]
In case anyone meets the same problem, here is the solution:

```
import * as React from "react";
import { useEffect } from "react";
import { useMap } from "react-map-gl/maplibre";
import MapLibreGlDirections from "@maplibre/maplibre-gl-directions";

export default function Directions() {
  const { mymap } = useMap();
  useEffect(() => {
    if (!mymap) return;
    mymap.on("load", () => {
      const directions = new MapLibreGlDirections(mymap.getMap());
      directions.interactive = true;

      directions.setWaypoints([
        [-87.6987661, 42.0054874],
        [-87.76756155000001, 41.531964550000004],
      ]);
      // console.log("setWaypoints end");
    });
  }, [mymap]);
}
```
