### ISSUE TITLE
Does not register mouse is hovering

### ISSUE THREAD

**Issue by joleeee** [maplibre/maplibre-gl-directions#232]
When moving a waypoint, you cannot move it again without first moving the cursor outside and then back inside (usually).

https://github.com/user-attachments/assets/26737977-8467-493a-809e-edf9104d84e8

**Comment by smellyshovel** [comment]
> without first moving the cursor outside and then back inside

Not necessarily. For me it's required to just *move* it (for at least 1px), even if the movement is still within the waypoint's bounds.

Not sure if that's a bug though. It's determined whether the cursor's hovering a waypoint by checking so on the mousemove event. And if there was no mousemove event (the cursor stays still, as it your example), then it's treated as if it's not (the defaul behavior).

A possible option here would be to re-check everytime after the mouseup event.

I'll take a look at what could be done here (though I'm not promising anything). Thanks for reporting.

P.S. PRs are welcome!

**Comment by smellyshovel** [comment]
https://github.com/maplibre/maplibre-gl-directions/releases/tag/v0.7.1 is now available.
