### ISSUE TITLE
Only some actions can be done while directions are loading

### ISSUE THREAD

**Issue by joleeee** [maplibre/maplibre-gl-directions#233]
I'm not even sure what is intended here. I want to be able to either disable any interactivity while stuff is loading, or let all interactivity be possible. Possibly allowing the movement of waypoints, but hiding the previous line while it is loading (thereby removing the ability to add new waypoints in the meanwhile).

I added a 5s delay to each request in devtools to make it easier to see.

https://github.com/user-attachments/assets/6c1b613a-c88c-4576-922d-58b076c80ea1

**Comment by smellyshovel** [comment]
https://github.com/maplibre/maplibre-gl-directions/releases/tag/v0.7.1 is now available.
