### ISSUE TITLE
Current Location / Following the route

### ISSUE THREAD

**Issue by Jab2870** [maplibre/maplibre-gl-directions#237]
Hi,

Is it possible to use this plugin to show the current position on a route, and perhaps the next step along a route, similarly to how the android (and presumably ios) sdks do:

![https://github.com/maplibre/maplibre-navigation-android](https://github.com/maplibre/maplibre-navigation-android/raw/main/.github/preview.png)

https://github.com/maplibre/maplibre-navigation-android

This clearly shows the current location along a route, and the next step for the route

**Comment by smellyshovel** [comment]
Hi!

Out of the box - no, it still hasn't been implemented (though there were plans to support it, it's just that it's a huge feature to implement and I don't have time to do that). Though a PR would be welcome.

On the other hand, it's just a matter of implementing your own Map Control to show the steps (this information is available from the routing response) and adding a source+layer to show the point moving along the routeline (here you should implement some way to find out the vehicle's actual location (GPS-based, I guess?)).

**Comment by Jab2870** [comment]
thanks for your quick response. Glad I wasn't just missing something. I doubt I have time to contribute anything like this in the short term, but who knows.

Thanks again
