### ISSUE TITLE
How to Limit Waypoints to Just Start and End Points in MapLibre GL Directions?

### ISSUE THREAD

**Issue by mashwishi** [maplibre/maplibre-gl-directions#238]
Hi there,

I'm working on a project using MapLibre GL with the @maplibre/maplibre-gl-directions library, and I'm trying to limit the waypoints to only include the start and end points of a route. Currently, my setup allows adding multiple waypoints, but I only need to have a start point and an end point.

Here’s a summary of my current implementation:

- MapDirection Component (mapdirection.tsx):
     - Initializes the map and adds the DistanceMeasurementMapLibreGlDirections control.
     - The DistanceMeasurementMapLibreGlDirections class is a custom extension of MapLibreGlDirections that adds distance measurement.
- Custom Directions Control ([distance-measurement-directions.ts](https://github.com/maplibre/maplibre-gl-directions/blob/main/demo/src/examples/12%20Distance%20Measurement.svelte)):
     - Extends MapLibreGlDirections to customize the route line rendering.

I have tried managing the waypoints manually by using event listeners, but I’m having trouble ensuring that only the start and end points are allowed. Here’s a snippet of the relevant code:

```tsx
// mapdirection.tsx
useEffect(() => {
  if (mapContainerRef.current && !map) {
    const initializeMap = new maplibregl.Map({
      // ...map initialization
    });

    initializeMap.on("load", () => {
      const newDirection = new DistanceMeasurementMapLibreGlDirections(
        initializeMap,
        config
      );

      newDirection.on("fetchroutesend", (ev) => {
        totalDistance = ev.data?.routes[0].distance as number;
      });

      newDirection.on("removewaypoint", () => {
        if (newDirection.waypoints.length < 2) {
          totalDistance = 0;
        }
      });

      newDirection.interactive = true;
      newDirection.allowRouteSwitch = false;

      setDirections(newDirection);
    });

    setMap(initializeMap);
  }
}, [map]);
```

I’m trying to figure out how to enforce that only two waypoints (start and end) are allowed. Ideally, I would like to prevent users from adding more than two waypoints or remove any extra waypoints if they are added.

Does anyone have any suggestions or examples of how to achieve this? I would appreciate any guidance or code snippets you could provide.

Thank you!

```json
  "dependencies": {
    "@maplibre/maplibre-gl-directions": "^0.7.1",
    "maplibre-gl": "^4.5.2",
    "next": "14.2.4",
    "next-themes": "^0.3.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwind-merge": "^2.5.2",
    "tailwindcss": "3.4.1",
    "tailwindcss-animate": "^1.0.7",
    "typescript": "5.3.3",
    ....
  },
  ```

**Comment by mashwishi** [comment]
I have tried this, but the functionality works 50/50 what i mean by that is i was able to apply max limit of 2 only start and end however when i start removing start and end i can no longer add a new route/direection

```tsx
        // Limit the number of waypoints to 2
        newDirection.on(
          "addwaypoint",
          (event: MapLibreGlDirectionsWaypointEvent) => {
            setWaypoints((prev) => {
              if (prev.length >= 2) {
                // Prevent more than 2 waypoints from being added
                newDirection.removeWaypoint(event.index);
                return prev;
              }
              return [...prev, event.index];
            });
          }
        );

        // Handle waypoint removal
        newDirection.on(
          "removewaypoint",
          (event: MapLibreGlDirectionsWaypointEvent) => {
            setWaypoints((prev) => prev.filter((_, i) => i !== event.index));
          }
        );
```

![limit 2](https://github.com/user-attachments/assets/a0d7bb31-8b69-4c4a-9648-eeaf873f9c7d)

**Comment by smellyshovel** [comment]
@mashwishi 

https://github.com/user-attachments/assets/95b936fd-f772-4b60-b4c7-9ebd3443a3b9

```
    directions.on("addwaypoint", (data) => {
        if (directions.waypoints.length > 2) {
          directions.removeWaypoint(data.data.index);
        }
      });
```

A quick solution. After adding a waypoint, check if there are more than 2 totally. If there are, then remove the added one right away.

Does the thing (you won't be able to add wayponints neither by clicking the map nor by dragging the hoverpoint), still allows to move the added ones, but makes some additional network requests (one of which cancels right away). And also the possibility to drag the hoverpoint while it actually doesn't do anything is "meh". I'll keep looking.

**Comment by smellyshovel** [comment]
@mashwishi 

Even better idea would be to redefine the `_addWaypoint` protected method in your `DistanceMeasurementDirections`.

```
async _addWaypoint(waypoint: [number, number], index?: number, originalEvent?: any): Promise<void> {
    this.abortController?.abort();

    index = index ?? this._waypoints.length;

    // * THE ADDED LINE *
    if (this.waypoints.length >= 2) return;

    this._waypoints.splice(
      index,
      0,
      this.buildPoint(
        waypoint,
        "WAYPOINT",
        this.configuration.bearings
          ? {
              bearing: undefined,
            }
          : undefined,
      ),
    );

    this.assignWaypointsCategories();

    const waypointEvent = new MapLibreGlDirectionsWaypointEvent("addwaypoint", originalEvent, {
      index,
    });
    this.fire(waypointEvent);

    this.draw();

    try {
      await this.fetchDirections(waypointEvent);
    } catch (err) {
      // noop
    }
  }
```

Take a look at the only added line. It does the trick.

But, there's still an issue with being able to drag the hoverpoint, even though it doesn't really do anything anymore. And there are 2 options to fix it, from what I can see: 1) use styling to just visually don't render it or 2) reimplement your custom class to properly handle it. I'm gonna try with the second option and will let you know whether it worked.

**Comment by smellyshovel** [comment]
Redefining the `draw` method does the trick.

```
  protected draw(skipSelectedRouteRedraw?: boolean) {
    // Nullify the hoverpoint so that it's never rendered.
    this.hoverpoint = undefined;
    super.draw(skipSelectedRouteRedraw);
  }
```

This, combined with the code above, gives the following result:

https://github.com/user-attachments/assets/f5840304-c15c-462e-8e34-5beb6fde81b6

Generally, the possibilities are endless here. Given the access to redefine internal implementations in the subclass allows you to do literally anything you'd like.

On the other hand, without extending the base class I feel like this would be (almost) impossible to achieve.

**Comment by mashwishi** [comment]
> @mashwishi
> 
>  dm.mp4 
> ```
>     directions.on("addwaypoint", (data) => {
>         if (directions.waypoints.length > 2) {
>           directions.removeWaypoint(data.data.index);
>         }
>       });
> ```
> 
> A quick solution. After adding a waypoint, check if there are more than 2 totally. If there are, then remove the added one right away.
> 
> Does the thing (you won't be able to add wayponints neither by clicking the map nor by dragging the hoverpoint), still allows to move the added ones, but makes some additional network requests (one of which cancels right away). And also the possibility to drag the hoverpoint while it actually doesn't do anything is "meh". I'll keep looking.

Yes actually this works fine, turns out i need to remove/update the condition remove and just add then remove the greater 2 in the add event.

I was able to so live tracking now and 2 waypoint (start/end) with no issues.

```tsx
        // Limit the number of waypoints to 2
        newDirection.on("addwaypoint", (event) => {
          const waypoints = newDirection.waypoints || [];
          setCords(waypoints.slice(0, 2).map((waypoint) => waypoint));
          if (waypoints.length > 2) {
            newDirection.setWaypoints(
              waypoints.slice(0, 2).map((waypoint) => waypoint)
            );
          }
        });

        // Handle waypoint removal
        newDirection.on("removewaypoint", (event) => {
          const waypoints = newDirection.waypoints || [];
          setCords(waypoints);
        });
```

![L2](https://github.com/user-attachments/assets/8bc609b4-e975-4a6a-bb15-94814ba037db)



Thanks!
