### ISSUE TITLE
Issue MapLibreGlDirections 

### ISSUE THREAD

**Issue by arezitopedia** [maplibre/maplibre-gl-directions#243]
How to call MapLibreGlDirections multiple times for displaying multiple routes of vehicules (different assets, cars, each with a different color)?

**Comment by smellyshovel** [comment]
Hi, @arezitopedia. Check this part of the docs
https://maplibre.org/maplibre-gl-directions/api/#md:customization

Also, I'm not sure if I totally get the use case, but it may be a good idea to just create multiple instances of the plugin and use them with the same map?

**Comment by arezitopedia** [comment]
@smellyshovel that was exactly what I needed, thank you very much!
